name: repo-checks

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry==1.5.0
          poetry install
      - name: Lint
        run: |
          poetry run ruff src tests
      - name: Typing
        run: |
          poetry run pyright src tests
      - name: Test with pytest
        run: |
          make unit-test
